import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "next/font/google"; // Import the Poppins font
import "./globals.css";
import Navbar from "@/components/Navbar";

// Load custom local fonts (Geist Sans and Geist Mono)
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Load Poppins font with the desired weights (light, regular, bold)
export const poppins = Poppins({
  weight: ["300", "400", "600"], // You can adjust the weights as needed
  subsets: ["latin"], // You can add other subsets like 'latin-ext' if needed
  variable: "--font-poppins", // Define a custom CSS variable for Poppins font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
